### ISSUE TITLE
Error al ejecutar la aplicación en el AVD 2.7 QVGA API 23

### ISSUE THREAD

**Issue by jarfernandez** [jarfernandez/DiscountCalculator#5]
Error al ejecutar la aplicación en el AVD 2.7 QVGA API 23:

E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.jarfernandez.discountcalculator, PID: 5000
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.jarfernandez.discountcalculator/com.jarfernandez.discountcalculator.activities.MainActivity}: android.content.res.Resources$NotFoundException: File res/drawable/ic_clear_text.xml from drawable resource ID #0x7f070062
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                      at android.app.ActivityThread.-wrap11(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:148)
                      at android.app.ActivityThread.main(ActivityThread.java:5417)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                   Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ic_clear_text.xml from drawable resource ID #0x7f070062
                      at android.content.res.Resources.loadDrawableForCookie(Resources.java:2640)
                      at android.content.res.Resources.loadDrawable(Resources.java:2540)
                      at android.content.res.Resources.getDrawable(Resources.java:806)
                      at android.content.res.Resources.getDrawable(Resources.java:771)
                      at com.jarfernandez.discountcalculator.activities.MainActivity.onCreate(MainActivity.java:63)
                      at android.app.Activity.performCreate(Activity.java:6237)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                      at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:148) 
                      at android.app.ActivityThread.main(ActivityThread.java:5417) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                   Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #0: <bitmap> requires a valid 'src' attribute
                      at android.graphics.drawable.BitmapDrawable.updateStateFromTypedArray(BitmapDrawable.java:764)
                      at android.graphics.drawable.BitmapDrawable.inflate(BitmapDrawable.java:724)
                      at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1215)
                      at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1124)
                      at android.content.res.Resources.loadDrawableForCookie(Resources.java:2630)
                      at android.content.res.Resources.loadDrawable(Resources.java:2540) 
                      at android.content.res.Resources.getDrawable(Resources.java:806) 
                      at android.content.res.Resources.getDrawable(Resources.java:771) 
                      at com.jarfernandez.discountcalculator.activities.MainActivity.onCreate(MainActivity.java:63) 
                      at android.app.Activity.performCreate(Activity.java:6237) 
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                      at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:148) 
                      at android.app.ActivityThread.main(ActivityThread.java:5417) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by jarfernandez** [comment]
Se corrige con el commit [0d3ea75](https://github.com/jarfernandez/DiscountCalculator/commit/0d3ea753f5f44eefab9b7cc4df95a6826abe170b).
